set(ARCHCFLAGS          "-mlong-calls -Wstrict-prototypes -Wno-attributes -Wno-unknown-pragmas -Wno-psabi")
set(ARCHCPUFLAGS        "-mlittle-endian -march=armv7-m -mtune=cortex-m3 -mfloat-abi=soft -mthumb -Wa,-mimplicit-it=always -Wall -Werror")
set(ARCHCXXFLAGS        "-mlong-calls -Wno-attributes -Wno-unknown-pragmas -nostdinc++ -Wno-psabi -fno-exceptions -fcheck-new -fno-rtti")
set(ARCHPICFLAGS        "-fpic -msingle-pic-base -mpic-register=r10")
set(ARCHWARNINGS        "")
set(ARCHWARNINGSXX      "")
set(ARCHOPTIMIZATION    "-Os -fno-strict-aliasing -fomit-frame-pointer -fno-common -Wall -Wshadow -Wundef -ffunction-sections -fdata-sections")
set(CROSSDEV            "arm-none-eabi-")
set(CMAKE_C_COMPILER    "arm-none-eabi-gcc")
set(CMAKE_CXX_COMPILER  "arm-none-eabi-g++")
set(CMAKE_LINKER        "arm-none-eabi-ld")
set(CMAKE_OBJCOPY       "arm-none-eabi-objcopy")
set(CMAKE_OBJDUMP       "arm-none-eabi-objdump")
set(NXFLATLDFLAGS1      "-r -d -warn-common")
set(NXFLATLDFLAGS2      "-r -d -warn-common -T/home/jhs/nuttx/nuttx_os/binfmt/libnxflat/gnu-nxflat-pcrel.ld -no-check-sections")
set(OBJEXT              ".o")
set(LIBEXT              ".a")
set(EXEEXT              "")
set(HOSTCC              "cc")
set(HOSTINCLUDES        "")
set(HOSTCFLAGS          "-O2 -Wall -Wstrict-prototypes -Wshadow -DHAVE_STRTOK_C=1 -DHAVE_STRNDUP=1")
set(HOSTLDFLAGS         "")
set(HOSTEXEEXT          "")
set(LDNAME              "gnu-elf.ld")
set(LDELFFLAGS          "-r /home/jhs/nuttx/nuttx_os/arch/arm/src/crt0.o -e _start ")
set(LDMODULEFLAGS       "-r")
set(NUTTX_ARCH          "arm")
set(NUTTX_ARCH_CHIP     "stm32")
set(NUTTX_BOARD         "stm32f103-alientek")
set(NUTTX_BUILD         "flat")
set(NUTTX_CXX           "cxx")
set(LLVM_ARCHTYPE       "thumbv7m")
set(LLVM_CPUTYPE        "cortex-m3")
set(LLVM_ABITYPE        "eabi")
set(EXTRA_LIBS       "/usr/lib/gcc/arm-none-eabi/10.3.1/thumb/v7-m/nofp/libgcc.a /usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/lib/thumb/v7-m/nofp/libm.a")
set(EXTRA_OBJS       "")
set(HEAD_OBJ         "")
set(LDENDGROUP       "")
set(LDFLAGS          "--entry=__start -nostdlib --gc-sections --cref -Map=/home/jhs/nuttx/nuttx_os/nuttx.map")
set(LDSTARTGROUP     "")
set(LDLIBS     "-lsched -ldrivers -lboards -lc -lmm -larch -lapps -lfs -lbinfmt -lboard -lboard ")
